"""
pact test_writer — generate regression tests for guards inserted by pact fix.

For each applied llm_response_unguarded fix, generates a pytest that:
  1. Constructs the object under test via __new__ (bypassing __init__ complexity)
  2. Patches the LLM response with an empty attr list
  3. Asserts the function returns None rather than raising IndexError

Usage
-----
    from pact.test_writer import generate_test_file
    test_src = generate_test_file(path, applied_violations, patched_source)
    Path("test_pact_guards.py").write_text(test_src)
"""

from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import NamedTuple


class _FuncContext(NamedTuple):
    name: str
    is_async: bool
    is_method: bool
    class_name: str | None
    params: list[str]


def _find_enclosing_function(source: str, line: int) -> _FuncContext | None:
    """Return the innermost function/method enclosing `line`."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return None

    best: tuple[int, _FuncContext] | None = None

    def _walk(nodes: list, class_name: str | None = None) -> None:
        nonlocal best
        for node in nodes:
            if isinstance(node, ast.ClassDef):
                _walk(node.body, node.name)
            elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                end = getattr(node, "end_lineno", node.lineno)
                if node.lineno <= line <= end:
                    span = end - node.lineno
                    params = [a.arg for a in node.args.args]
                    ctx = _FuncContext(
                        name=node.name,
                        is_async=isinstance(node, ast.AsyncFunctionDef),
                        is_method=class_name is not None,
                        class_name=class_name,
                        params=params,
                    )
                    if best is None or span < best[0]:
                        best = (span, ctx)
                _walk(node.body, class_name)

    _walk(tree.body)
    return best[1] if best else None


_PAT = re.compile(r"^(\w+)\.(\w+)\[0\]$")


def generate_test_file(
    path: str,
    applied: list,
    patched_source: str,
) -> str:
    """
    Generate a pytest module proving each applied llm_response_unguarded guard.

    Parameters
    ----------
    path:
        Source file path (used for import derivation and comments).
    applied:
        List of FailureEvidence objects whose fixes were applied.
    patched_source:
        The already-patched source text (guards already inserted).

    Returns
    -------
    A string of Python test source, or "" if no tests can be generated.
    """
    llm_evs = [ev for ev in applied if _mode_name(ev) == "llm_response_unguarded"]
    if not llm_evs:
        return ""

    lines: list[str] = [
        '"""Regression tests generated by pact fix — do not delete."""',
        "",
        "import pytest",
        "from unittest.mock import MagicMock",
        "",
    ]

    seen_tests: set[str] = set()

    for ev in llm_evs:
        m = _PAT.match(ev.call)
        if not m:
            continue
        var, attr = m.group(1), m.group(2)

        ctx = _find_enclosing_function(patched_source, ev.line)
        if ctx is None:
            continue

        test_name = f"test_{ctx.name}_guards_empty_{attr}"
        if test_name in seen_tests:
            continue
        seen_tests.add(test_name)

        rel = Path(path).name
        decorator = "@pytest.mark.asyncio\n" if ctx.is_async else ""
        async_def = "async def" if ctx.is_async else "def"
        await_kw = "await " if ctx.is_async else ""

        if ctx.is_method and ctx.class_name:
            setup = _method_setup(ctx, var, attr, patched_source, path, ev.line)
            call = f"{await_kw}instance.{ctx.name}({_dummy_call_args(ctx)})"
        else:
            setup = _func_setup(var, attr)
            call = f"{await_kw}{ctx.name}({_dummy_call_args(ctx)})"

        lines += [
            f"{decorator}{async_def} {test_name}():",
            '    """',
            f"    pact regression: {rel}:{ev.line}",
            f"    Guard: if not {var}.{attr}: return",
            f"    Without guard: IndexError when LLM returns empty {attr} (content filter, rate limit, etc.)",
            '    """',
        ]
        lines += [f"    {ln}" for ln in setup]
        lines += [
            f"    result = {call}",
            "    assert result is None, (",
            f'        "Guard must return None on empty {attr}, not raise IndexError"',
            "    )",
            "",
        ]

    if len(lines) <= 6:
        return ""

    return "\n".join(lines) + "\n"


def _resolve_class(source: str, path: str, line: int) -> tuple[str, str] | None:
    """
    Use Jedi to resolve the class of `self` at `line`.
    Returns (module_name, class_name) or None if resolution fails.
    """
    try:
        import jedi
    except ImportError:
        return None
    try:
        script = jedi.Script(source=source, path=path)
        names = script.infer(line=line, column=8)
        for n in names:
            if n.module_name and n.name and n.type == "class":
                return (n.module_name, n.name)
    except Exception:  # noqa — jedi inference raises unpredictably on malformed source
        pass
    return None


def _method_setup(
    ctx: _FuncContext,
    var: str,
    attr: str,
    source: str = "",
    path: str = "",
    line: int = 0,
) -> list[str]:
    resolved = _resolve_class(source, path, line) if source and path else None
    if resolved:
        mod, cls = resolved
        lines = [
            "try:",
            f"    from {mod} import {cls}",
            f"    instance = {cls}.__new__({cls})",
            "except Exception:",
            "    instance = MagicMock(spec_set=False)",
        ]
    else:
        lines = [
            f"# Bypass __init__ — we only need to set {var}",
            "instance = MagicMock(spec_set=False)",
        ]
    lines += [
        f"mock_{var} = MagicMock()",
        f"mock_{var}.{attr} = []",
        f"instance.{var} = mock_{var}",
    ]
    return lines


def _func_setup(var: str, attr: str) -> list[str]:
    return [
        f"mock_{var} = MagicMock()",
        f"mock_{var}.{attr} = []",
    ]


def _dummy_call_args(ctx: _FuncContext) -> str:
    params = [p for p in ctx.params if p not in ("self", "cls")]
    return ", ".join("MagicMock()" for _ in params)


def _mode_name(ev) -> str:
    return getattr(ev, "mode_name", None) or getattr(ev, "context", "")
